-----------------------------------------------------------------------------------------
--- this doc is for propensity model, regardless of the subcatogory  -----
-----------------------------------------------------------------------------------------


---- 1. define the test date point
DECLARE @CUT_DATE AS DATE
SET @CUT_DATE=CONVERT(DATE, Cast('2015-02-20' as datetime)) 

---- 2. select the txn data of the 523,951 from CUT_DATE rolling back 12 months
drop table #HIST_PUR
select 
B.PUR_CST_ID, 
B.PUR_ID, 
B.PUR_DT, 
B.PUR_CNT_ID, 
B.SKU_ID, 
B.SKU_PRICE, 
B.TOTAL_PUR_AMOUNT, 
B.LPK_AMOUNT, 
B.LPK_QTY, 
B.LIN_ID, 
B.FRANCHISEEN,
B.PCT_ID_ROUTINE,
B.ROUTINEEN,
B.PCT_ID_CATEGORY
into #HIST_PUR
from 
[SQL02_TEMP].[dbo].[V_LOP_SYS_PURCHASE_2015_pop_sample] A
LEFT JOIN
SQL02_TEMP..V_LOP_SYS_PURCHASE_ALL_TOTAL B
on A.PUR_CST_ID = B.PUR_CST_ID
where CONVERT(date,B.PUR_DT)<@CUT_DATE and CONVERT(date,B.PUR_DT) > DATEADD(DAY,-360,@CUT_DATE)

---- 3. merge table with Age and purchase catogory table
--drop table #HIST_MEX
--DECLARE @CUT_DATE AS DATE
--SET @CUT_DATE=CONVERT(DATE, Cast('2015-06-30' as datetime)) 
drop table #HIST_MEX
select E.*, 
F.CHANNEL,
datediff(DAY,CONVERT(date,PUR_DT),@CUT_DATE) as PUR_DISC_DAY,
CEILING(datediff(DAY,CONVERT(date,PUR_DT),@CUT_DATE)/30.0) as PUR_DISC_MONTH
into #HIST_MEX
from 
--2
(
--1
select C.*,D.pur_dt as PUR_DT_FST
from
(
select A.*,B.AGE
from
#HIST_PUR A
LEFT JOIN
LOREALPARIS_PROD..V_AGE_BAND B
on A.PUR_CST_ID = B.CST_ID
) C
--1
LEFT JOIN
SQL02_TEMP..V_LOP_FIRST_PUR D
on C.PUR_CST_ID = D.pur_cst_id
) E
--2
LEFT JOIN
[SQL02_TEMP].[dbo].[V_REF_CHANNEL] F
on E.PUR_CNT_ID = F.CNT_ID

---------- test 1 --- 351,016
--select count(distinct PUR_CST_ID) from #HIST_MEX
------------------

---- 4. derive variables on CUSTOMER level
---- 4.2.1 group the table on p12 level
drop table #VAR_P12_MONTH
select 

PUR_CST_ID,
PUR_DISC_MONTH,

--- total criteria
SUM(LPK_AMOUNT) as AMT_TXN,
SUM(LPK_QTY) as NUM_SKU,
COUNT(DISTINCT PUR_ID) AS NUM_TRIP,
COUNT(DISTINCT SKU_ID) AS RANGE_SKU,
SUM(CASE WHEN CHANNEL='TMALL' THEN LPK_AMOUNT ELSE 0 END) as AMT_TMALL,
SUM(CASE WHEN CHANNEL='DEPARTMENT STORE' THEN LPK_AMOUNT ELSE 0 END) as AMT_DS,
SUM(CASE WHEN CHANNEL='MODERN TRADE' THEN LPK_AMOUNT ELSE 0 END) as AMT_MD,
--- divide by Franchise and Routine
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 57 THEN LPK_AMOUNT ELSE 0 END) as AMT_RV_DERMA,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1021 THEN LPK_AMOUNT ELSE 0 END) as AMT_RV_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1026 THEN LPK_AMOUNT ELSE 0 END) as AMT_RV_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1046 THEN LPK_AMOUNT ELSE 0 END) as AMT_RV_FILLER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 32 THEN LPK_AMOUNT ELSE 0 END) as AMT_HF,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 71 THEN LPK_AMOUNT ELSE 0 END) as AMT_WP_NORMAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1024 THEN LPK_AMOUNT ELSE 0 END) as AMT_WP_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1023 THEN LPK_AMOUNT ELSE 0 END) as AMT_WP_CLINICAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1039 THEN LPK_AMOUNT ELSE 0 END) as AMT_WP_MIRACLE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID in (68,1042) THEN LPK_AMOUNT ELSE 0 END) as AMT_UV,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 153 THEN LPK_AMOUNT ELSE 0 END) as AMT_AP_BASIC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1049 THEN LPK_AMOUNT ELSE 0 END) as AMT_AP_CELL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1050 THEN LPK_AMOUNT ELSE 0 END) as AMT_AP_LUMI,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1051 THEN LPK_AMOUNT ELSE 0 END) as AMT_AP_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 998 THEN LPK_AMOUNT ELSE 0 END) as AMT_YC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND LIN_ID NOT IN(57,1021,1026,1046,32,71,1023,1024,1039,68,1042,153,1049,1050,1051,998) THEN LPK_AMOUNT ELSE 0 END) as AMT_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(11) THEN LPK_AMOUNT ELSE 0 END) as AMT_CLEANSER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(12) THEN LPK_AMOUNT ELSE 0 END) as AMT_ESSENCE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(15) THEN LPK_AMOUNT ELSE 0 END) as AMT_MOISTURIZER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(17) THEN LPK_AMOUNT ELSE 0 END) as AMT_TONER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(27) THEN LPK_AMOUNT ELSE 0 END) as AMT_SPCL_CARE_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(21) THEN LPK_AMOUNT ELSE 0 END) as AMT_MU_FACE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(20) THEN LPK_AMOUNT ELSE 0 END) as AMT_MU_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(22) THEN LPK_AMOUNT ELSE 0 END) as AMT_MU_LIP,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(23) THEN LPK_AMOUNT ELSE 0 END) as AMT_MU_NAIL,
SUM(CASE WHEN PCT_ID_CATEGORY=6 THEN LPK_AMOUNT ELSE 0 END) as AMT_MENS,
SUM(CASE WHEN PCT_ID_CATEGORY=5 THEN LPK_AMOUNT ELSE 0 END) as AMT_HAIR_COLOR,
SUM(CASE WHEN PCT_ID_CATEGORY=8 THEN LPK_AMOUNT ELSE 0 END) as AMT_HAIR_CARE

into #VAR_P12_MONTH
from #HIST_MEX
group by PUR_CST_ID,PUR_DISC_MONTH

---- 4.2.2 group the table on CUST level -- 351,016
drop table #VAR_CUST_P12
select 
PUR_CST_ID,
--- monthly criteria,
SUM(AMT_TMALL) as P12_AMT_TMALL,
SUM(AMT_DS) as P12_AMT_DS,
SUM(AMT_MD) as P12_AMT_MD,
SUM(AMT_TXN) as P12_SUM_AMT_TXN,
sum(NUM_SKU) as P12_SUM_NUM_SKU,
sum(NUM_TRIP) as P12_SUM_NUM_TRIP,
avg(RANGE_SKU) as P12_AVG_RANGE_SKU,
sum(AMT_RV_DERMA) as P12_AMT_RV_DERMA,
sum(AMT_RV_LASER) as P12_AMT_RV_LASER,
sum(AMT_RV_OTHER) as P12_AMT_RV_OTHER,
sum(AMT_RV_FILLER) as P12_AMT_RV_FILLER,
sum(AMT_HF) as P12_AMT_HF,
sum(AMT_WP_NORMAL) as P12_AMT_WP_NORMAL,
sum(AMT_WP_LASER) as P12_AMT_WP_LASER,
sum(AMT_WP_CLINICAL) as P12_AMT_WP_CLINICAL,
sum(AMT_WP_MIRACLE) as P12_AMT_WP_MIRACLE,
sum(AMT_UV) as P12_AMT_UV,
sum(AMT_AP_BASIC) as P12_AMT_AP_BASIC,
sum(AMT_AP_CELL) as P12_AMT_AP_CELL,
sum(AMT_AP_LUMI) as P12_AMT_AP_LUMI,
sum(AMT_AP_OTHER) as P12_AMT_AP_OTHER,
sum(AMT_YC) as P12_AMT_YC,
sum(AMT_OTHER) as P12_AMT_OTHER,
sum(AMT_CLEANSER) as P12_AMT_CLEANSER,
sum(AMT_ESSENCE) as P12_AMT_ESSENCE,
sum(AMT_MOISTURIZER) as P12_AMT_MOISTURIZER,
sum(AMT_TONER) as P12_AMT_TONER,
sum(AMT_SPCL_CARE_EYE) as P12_AMT_SPCL_CARE_EYE,
sum(AMT_MU_FACE) as P12_AMT_MU_FACE,
sum(AMT_MU_EYE) as P12_AMT_MU_EYE,
sum(AMT_MU_LIP) as P12_AMT_MU_LIP,
sum(AMT_MU_NAIL) as P12_AMT_MU_NAIL,
sum(AMT_MENS) as P12_AMT_MENS,
sum(AMT_HAIR_COLOR) as P12_AMT_HAIR_COLOR,
sum(AMT_HAIR_CARE) as P12_AMT_HAIR_CARE,
stdev(AMT_TXN) as std_AMT_TXN,
stdev(NUM_SKU) as std_NUM_SKU,
stdev(NUM_TRIP) as std_NUM_TRIP,
stdev(RANGE_SKU) as std_RANGE_SKU,
stdev(AMT_TMALL) as std_AMT_TMALL,
stdev(AMT_DS) as std_AMT_DS,
stdev(AMT_MD) as std_AMT_MD,
stdev(AMT_RV_DERMA) as std_AMT_RV_DERMA,
stdev(AMT_RV_LASER) as std_AMT_RV_LASER,
stdev(AMT_RV_OTHER) as std_AMT_RV_OTHER,
stdev(AMT_RV_FILLER) as std_AMT_RV_FILLER,
stdev(AMT_HF) as std_AMT_HF,
stdev(AMT_WP_NORMAL) as std_AMT_WP_NORMAL,
stdev(AMT_WP_LASER) as std_AMT_WP_LASER,
stdev(AMT_WP_CLINICAL) as std_AMT_WP_CLINICAL,
stdev(AMT_WP_MIRACLE) as std_AMT_WP_MIRACLE,
stdev(AMT_UV) as std_AMT_UV,
stdev(AMT_AP_BASIC) as std_AMT_AP_BASIC,
stdev(AMT_AP_CELL) as std_AMT_AP_CELL,
stdev(AMT_AP_LUMI) as std_AMT_AP_LUMI,
stdev(AMT_AP_OTHER) as std_AMT_AP_OTHER,
stdev(AMT_YC) as std_AMT_YC,
stdev(AMT_OTHER) as std_AMT_OTHER,
stdev(AMT_CLEANSER) as std_AMT_CLEANSER,
stdev(AMT_ESSENCE) as std_AMT_ESSENCE,
stdev(AMT_MOISTURIZER) as std_AMT_MOISTURIZER,
stdev(AMT_TONER) as std_AMT_TONER,
stdev(AMT_SPCL_CARE_EYE) as std_AMT_SPCL_CARE_EYE,
stdev(AMT_MU_FACE) as std_AMT_MU_FACE,
stdev(AMT_MU_EYE) as std_AMT_MU_EYE,
stdev(AMT_MU_LIP) as std_AMT_MU_LIP,
stdev(AMT_MU_NAIL) as std_AMT_MU_NAIL,
stdev(AMT_MENS) as std_AMT_MENS,
stdev(AMT_HAIR_COLOR) as std_AMT_HAIR_COLOR,
stdev(AMT_HAIR_CARE) as std_AMT_HAIR_CARE
into #VAR_CUST_P12
from #VAR_P12_MONTH
group by PUR_CST_ID


---- 4.2.2 group the table on p3 level
drop table #VAR_CUST_P3
select PUR_CST_ID as P3_PUR_CST_ID,
SUM(isnull(LPK_AMOUNT,0)) as P3_AMT_TXN,
sum(isnull(LPK_QTY,0)) as P3_NUM_SKU,
count(DISTINCT PUR_ID) as P3_NUM_TRIP,
count(DISTINCT SKU_ID) as P3_RANGE_SKU,
SUM(CASE WHEN CHANNEL='TMALL' THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_TMALL,
SUM(CASE WHEN CHANNEL='DEPARTMENT STORE' THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_DS,
SUM(CASE WHEN CHANNEL='MODERN TRADE' THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_MD,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 57 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_RV_DERMA,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1021 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_RV_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1026 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_RV_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1046 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_RV_FILLER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 32 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_HF,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 71 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_WP_NORMAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1024 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_WP_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1023 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_WP_CLINICAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1039 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_WP_MIRACLE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID in (68,1042) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_UV,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 153 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_AP_BASIC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1049 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_AP_CELL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1050 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_AP_LUMI,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1051 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_AP_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 998 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_YC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND LIN_ID NOT IN(57,1021,1026,1046,32,71,1023,1024,1039,68,1042,153,1049,1050,1051,998) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(11) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_CLEANSER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(12) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_ESSENCE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(15) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_MOISTURIZER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(17) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_TONER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(27) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_SPCL_CARE_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(21) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_MU_FACE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(20) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_MU_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(22) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_MU_LIP,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(23) THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_MU_NAIL,
SUM(CASE WHEN PCT_ID_CATEGORY=6 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_MENS,
SUM(CASE WHEN PCT_ID_CATEGORY=5 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_HAIR_COLOR,
SUM(CASE WHEN PCT_ID_CATEGORY=8 THEN LPK_AMOUNT ELSE 0 END) as P3_AMT_HAIR_CARE 
into #VAR_CUST_P3
from
( select * 
from #HIST_MEX
where PUR_DISC_DAY <= 90 ) #tmp_3
group by PUR_CST_ID


---- 4.2.3 group the table on p1 level
drop table #VAR_CUST_P1
select PUR_CST_ID as P1_PUR_CST_ID,
SUM(LPK_AMOUNT) as P1_AMT_TXN,
sum(LPK_QTY) as P1_NUM_SKU,
count(DISTINCT PUR_ID) as P1_NUM_TRIP,
count(DISTINCT SKU_ID) as P1_RANGE_SKU,
SUM(CASE WHEN CHANNEL='TMALL' THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_TMALL,
SUM(CASE WHEN CHANNEL='DEPARTMENT STORE' THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_DS,
SUM(CASE WHEN CHANNEL='MODERN TRADE' THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_MD,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 57 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_RV_DERMA,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1021 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_RV_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1026 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_RV_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1046 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_RV_FILLER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 32 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_HF,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 71 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_WP_NORMAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1024 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_WP_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1023 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_WP_CLINICAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1039 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_WP_MIRACLE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID in (68,1042) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_UV,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 153 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_AP_BASIC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1049 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_AP_CELL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1050 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_AP_LUMI,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1051 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_AP_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 998 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_YC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND LIN_ID NOT IN(57,1021,1026,1046,32,71,1023,1024,1039,68,1042,153,1049,1050,1051,998) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(11) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_CLEANSER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(12) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_ESSENCE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(15) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_MOISTURIZER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(17) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_TONER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(27) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_SPCL_CARE_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(21) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_MU_FACE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(20) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_MU_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(22) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_MU_LIP,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(23) THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_MU_NAIL,
SUM(CASE WHEN PCT_ID_CATEGORY=6 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_MENS,
SUM(CASE WHEN PCT_ID_CATEGORY=5 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_HAIR_COLOR,
SUM(CASE WHEN PCT_ID_CATEGORY=8 THEN LPK_AMOUNT ELSE 0 END) as P1_AMT_HAIR_CARE
into #VAR_CUST_P1
from
( select * 
from #HIST_MEX
where PUR_DISC_DAY <= 30 ) #tmp_1
group by PUR_CST_ID


---- 4.2.4 get the demographics data
--DECLARE @CUT_DATE AS DATE
--SET @CUT_DATE=CONVERT(DATE, Cast('2015-06-30' as datetime)) 

drop table #VAR_CUST_DEMO
select PUR_CST_ID as Demo_PUR_CST_ID,
max(AGE) as AGE,
max(datediff(DAY,PUR_DT_FST, @CUT_DATE)/365.0) as MEM_TENURE
into #VAR_CUST_DEMO
from #HIST_MEX
group by PUR_CST_ID

---- 4.3 merge all variables together
drop table #VAR_CUST_ALL
SELECT p12.*, p3.*, p1.*, demo.*
into #VAR_CUST_ALL
FROM #VAR_CUST_P12  p12
    LEFT JOIN #VAR_CUST_P3 p3
        ON p3.P3_PUR_CST_ID = p12.PUR_CST_ID
    LEFT JOIN #VAR_CUST_P1 p1
        ON p1.P1_PUR_CST_ID = p12.PUR_CST_ID
    LEFT JOIN #VAR_CUST_DEMO demo
        ON demo.Demo_PUR_CST_ID = p12.PUR_CST_ID
        
---- 4.3.1 drop extra join keys
ALTER TABLE #VAR_CUST_ALL DROP COLUMN P3_PUR_CST_ID,P1_PUR_CST_ID,Demo_PUR_CST_ID

---- 4.4 derive target variable
---- 4.4.1 cut next 2 weeks as target time window
--DECLARE @CUT_DATE AS DATE
--SET @CUT_DATE=CONVERT(DATE, Cast('2015-06-30' as datetime)) 
drop table #TARGET_PUR
select 
B.PUR_CST_ID, 
B.PUR_CNT_ID, 
B.LPK_QTY, 
B.LIN_ID,
PCT_ID_CATEGORY,
PCT_ID_ROUTINE
into #TARGET_PUR
from 
(
select PUR_CST_ID from #VAR_CUST_ALL
) A
LEFT JOIN
SQL02_TEMP..V_LOP_SYS_PURCHASE_ALL_TOTAL B
on A.PUR_CST_ID = B.PUR_CST_ID
where CONVERT(date,B.PUR_DT)> @CUT_DATE and CONVERT(date,B.PUR_DT) < DATEADD(DAY,14,@CUT_DATE)

---- 4.4.2 get CUST's next 2 week purchase bahavior
drop table #TARGET_PUR_CNT
select 
PUR_CST_ID,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 57 THEN 1 ELSE 0 END) as CNT_RV_DERMA,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1021 THEN 1 ELSE 0 END) as CNT_RV_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1026 THEN 1 ELSE 0 END) as CNT_RV_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1046 THEN 1 ELSE 0 END) as CNT_RV_FILLER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 32 THEN 1 ELSE 0 END) as CNT_HF,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 71 THEN 1 ELSE 0 END) as CNT_WP_NORMAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1024 THEN 1 ELSE 0 END) as CNT_WP_LASER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1023 THEN 1 ELSE 0 END) as CNT_WP_CLINICAL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1039 THEN 1 ELSE 0 END) as CNT_WP_MIRACLE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID in (68,1042) THEN 1 ELSE 0 END) as CNT_UV,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 153 THEN 1 ELSE 0 END) as CNT_AP_BASIC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1049 THEN 1 ELSE 0 END) as CNT_AP_CELL,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1050 THEN 1 ELSE 0 END) as CNT_AP_LUMI,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 1051 THEN 1 ELSE 0 END) as CNT_AP_OTHER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 and LIN_ID = 998 THEN 1 ELSE 0 END) as CNT_YC,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(11) THEN 1 ELSE 0 END) as CNT_CLEANSER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(12) THEN 1 ELSE 0 END) as CNT_ESSENCE,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(15) THEN 1 ELSE 0 END) as CNT_MOISTURIZER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(17) THEN 1 ELSE 0 END) as CNT_TONER,
SUM(CASE WHEN PCT_ID_CATEGORY=1 AND PCT_ID_ROUTINE IN(27) THEN 1 ELSE 0 END) as CNT_SPCL_CARE_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(21) THEN 1 ELSE 0 END) as CNT_MU_FACE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(20) THEN 1 ELSE 0 END) as CNT_MU_EYE,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(22) THEN 1 ELSE 0 END) as CNT_MU_LIP,
SUM(CASE WHEN PCT_ID_CATEGORY=3 AND PCT_ID_ROUTINE IN(23) THEN 1 ELSE 0 END) as CNT_MU_NAIL,
SUM(CASE WHEN PCT_ID_CATEGORY=6 THEN 1 ELSE 0 END) as CNT_MENS,
SUM(CASE WHEN PCT_ID_CATEGORY=5 THEN 1 ELSE 0 END) as CNT_HAIR_COLOR,
SUM(CASE WHEN PCT_ID_CATEGORY=8 THEN 1 ELSE 0 END) as CNT_HAIR_CARE
into #TARGET_PUR_CNT
from #TARGET_PUR
group by PUR_CST_ID

---- 4.4.2 TAG the CUST
drop table #TARGET_PUR_TAG
select 
PUR_CST_ID as TAG_PUR_CST_ID,
case when CNT_RV_DERMA >0 then 1 else 0 end as TAG_RV_DERMA,
case when CNT_RV_LASER >0 then 1 else 0 end as TAG_RV_LASER,
case when CNT_RV_OTHER >0 then 1 else 0 end as TAG_RV_OTHER,
case when CNT_RV_FILLER >0 then 1 else 0 end as TAG_RV_FILLER,
case when CNT_HF >0 then 1 else 0 end as TAG_HF,
case when CNT_WP_NORMAL >0 then 1 else 0 end as TAG_WP_NORMAL,
case when CNT_WP_LASER >0 then 1 else 0 end as TAG_WP_LASER,
case when CNT_WP_CLINICAL >0 then 1 else 0 end as TAG_WP_CLINICAL,
case when CNT_WP_MIRACLE >0 then 1 else 0 end as TAG_WP_MIRACLE,
case when CNT_UV >0 then 1 else 0 end as TAG_UV,
case when CNT_AP_BASIC >0 then 1 else 0 end as TAG_AP_BASIC,
case when CNT_AP_CELL >0 then 1 else 0 end as TAG_AP_CELL,
case when CNT_AP_LUMI >0 then 1 else 0 end as TAG_AP_LUMI,
case when CNT_AP_OTHER >0 then 1 else 0 end as TAG_AP_OTHER,
case when CNT_YC >0 then 1 else 0 end as TAG_YC,
case when CNT_CLEANSER >0 then 1 else 0 end as TAG_CLEANSER,
case when CNT_ESSENCE >0 then 1 else 0 end as TAG_ESSENCE,
case when CNT_MOISTURIZER >0 then 1 else 0 end as TAG_MOISTURIZER,
case when CNT_TONER >0 then 1 else 0 end as TAG_TONER,
case when CNT_SPCL_CARE_EYE >0 then 1 else 0 end as TAG_SPCL_CARE_EYE,
case when CNT_MU_FACE >0 then 1 else 0 end as TAG_MU_FACE,
case when CNT_MU_EYE >0 then 1 else 0 end as TAG_MU_EYE,
case when CNT_MU_LIP >0 then 1 else 0 end as TAG_MU_LIP,
case when CNT_MU_NAIL >0 then 1 else 0 end as TAG_MU_NAIL,
case when CNT_MENS >0 then 1 else 0 end as TAG_MENS,
case when CNT_HAIR_COLOR >0 then 1 else 0 end as TAG_HAIR_COLOR,
case when CNT_HAIR_CARE >0 then 1 else 0 end as TAG_HAIR_CARE
into #TARGET_PUR_TAG
from #TARGET_PUR_CNT

---- 5 MERGE with the variable list

select A.*, B.*
into [SQL02_TEMP].[dbo].[V_INPUT_MODEL_20150220]  
from
#VAR_CUST_ALL A
LEFT JOIN
#TARGET_PUR_TAG B
on A.PUR_CST_ID = B.TAG_PUR_CST_ID

ALTER TABLE [SQL02_TEMP].[dbo].[V_INPUT_MODEL_20150220] DROP COLUMN TAG_PUR_CST_ID


